#!/bin/sh
echo -e "Garuda will fly"

paru -S --norebuild --needed --batchinstall --redownload=no   \
    bat \
    diff-so-fancy \
    grv \
    lazydocker-bin \
    lazygit \
    docker-compose \
    fnm-bin \
    github-cli \
    mycli \
    neovim \
    pnpm \
    the_silver_searcher \
    tmux \
    tree \
    docker \
    inlets \
    asdf-vm \
    fd \
    ripgrep-all-bin \
    gitea-tea

